version: "2.0"
services:

    # Postgres
    postgres:
        image: postgres:11
        container_name: Postgres
        restart: always
        environment:
            - POSTGRES_USER=sample
            - POSTGRES_PASSWORD=sample
            - POSTGRES_DB=sample
        ports:
            - "5400:5432"
        volumes:
            - ../postgres/data:/var/lib/postgresql/data 
            - ../postgres/scripts/init.sh /docker-entrypoint-initdb.d/
    
    # Redis
    redis:
        image: 'bitnami/redis:latest'
        container_name: Redis
        environment:
            - REDIS_PASSWORD=sample
        ports:
            - "6300:6379"
        volumes:
            - ../redis:/bitnami/redis
